<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>uuid</key>
        <string>2EFE7357-C784-409D-9377-44DF62C0441E</string>
        <key>fileTypes</key>
        <array>
            <string>ttl</string>
        </array>
        <key>name</key>
        <string>TeraTerm</string>
        <key>scopeName</key>
        <string>source.ttl</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>name</key>
                <string>comment.line.semicolon.ttl</string>
                <key>match</key>
                <string>;.*</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.command.communication.ttl</string>
                <key>match</key>
                <string>\b(?i)(?:bplusrecv|bplussend|callmenu|changedir|clearscreen|closett|connect|cygconnect|disconnect|dispstr|enablekeyb|flushrecv|gethostname|getmodemstatus|gettitle|kmtfinish|kmtget|kmtrecv|kmtsend|loadkeymap|logautoclosemode|logclose|loginfo|logopen|logpause|logrotate|logstart|logwrite|quickvanrecv|quickvansend|recvln|restoresetup|scprecv|scpsend|send|sendbreak|sendbroadcast|sendfile|sendkcode|sendln|sendlnbroadcast|sendmulticast|setbaud|setdebug|setdtr|setecho|setmulticastname|setrts|setsync|settitle|showtt|testlink|unlink|wait|wait4all|waitevent|waitln|waitn|waitrecv|waitregex|xmodemrecv|xmodemsend|ymodemrecv|ymodemsend|zmodemrecv|zmodemsend)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.control.ttl</string>
                <key>match</key>
                <string>\b(?i)(?:break|call|continue|do|loop|end|execcmnd|exit|for|next|goto|if|then|elseif|else|endif|include|mpause|pause|return|until|enduntil|while|endwhile)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.command.stringoperator.ttl</string>
                <key>match</key>
                <string>\b(?i)(?:code2str|expandenv|int2str|regexoption|sprintf|sprintf2|str2code|str2int|strcompare|strconcat|strcopy|strinsert|strjoin|strlen|strmatch|strremove|strreplace|strscan|strspecial|strsplit|strtrim|tolower|toupper)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.command.fileoperator.ttl</string>
                <key>match</key>
                <string>\b(?i)(?:basename|dirname|fileclose|fileconcat|filecopy|filecreate|filedelete|filelock|filemarkptr|fileopen|filereadln|fileread|filerename|filesearch|fileseek|fileseekback|filestat|filestrseek|filestrseek2|filetruncate|fileunlock|filewrite|filewriteln|findfirst|findnext|findclose|foldercreate|folderdelete|foldersearch|getdir|getfileattr|makepath|setdir|setfileattr)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.command.password.ttl</string>
                <key>match</key>
                <string>\b(?i)(?:delpassword|getpassword|ispassword|passwordbox|setpassword)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.command.miscellaneous.ttl</string>
                <key>match</key>
                <string>\b(?i)(?:beep|bringupbox|checksum8|checksum8file|checksum16|checksum16file|checksum32|checksum32file|closesbox|clipb2var|crc16|crc16file|crc32|crc32file|exec|dirnamebox|filenamebox|getdate|getenv|getipv4addr|getipv6addr|getspecialfolder|gettime|getttdir|getver|ifdefined|inputbox|intdim|listbox|messagebox|random|rotateleft|rotateright|setdate|setdlgpos|setenv|setexitcode|settime|show|statusbox|strdim|uptime|var2clipb|yesnobox)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>support.variable.ttl</string>
                <key>match</key>
                <string>\b(?i)(?:groupmatchstr[1-9]|inputstr|matchstr|param[1-9]|paramcnt|result|timeout|mtimeout)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>entity.name.function.ttl</string>
                <key>match</key>
                <string>\B:\w+\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>string.quoted.ttl</string>
                <key>begin</key>
                <string>'|"</string>
                <key>beginCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.begin.ttl</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>'|"</string>
                <key>endCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.end.ttl</string>
                    </dict>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>constant.numeric.character.ttl</string>
                <key>match</key>
                <string>(#+)([0-9]+\.?[0-9]*)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>constant.numeric.ttl</string>
                <key>match</key>
                <string>\b((\$[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+)))\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.operator.ttl</string>
                <key>match</key>
                <string>\b(not|~|!|\+|-|\*|\/|%|&gt;&gt;&gt;|&gt;&gt;|&lt;&lt;|and|&amp;|xor|\^|or|\|\||\||==|!=|&lt;=|&gt;=|=|&lt;&gt;|&gt;|&lt;|&amp;&amp;)\b</string>
            </dict>
        </array>
    </dict>
</plist>
